<?php
/**
 * @package  : OMGF
 * @author   : Daan van den Bergh
 * @copyright: (c) 2019 Daan van den Bergh
 * @url      : https://daan.dev
 */

defined('ABSPATH') || exit;

class OMGF_AJAX_Generate extends OMGF_AJAX
{
    /** @var array $fonts */
    private $fonts = [];

    /**
     * OMGF_AJAX_Generate_Styles constructor.
     */
    public function __construct()
    {
        parent::__construct();

        $this->init();
    }

    /**
     * Generate the Stylesheet
     */
    private function init()
    {
        header("Content-type: text/css");

        $this->insert_promo();

        $selectedFonts = $this->db->get_total_fonts();

        $this->process_fonts($selectedFonts);

        $fonts = implode("\n", $this->fonts);
        $file  = OMGF_UPLOAD_DIR . '/' . OMGF_FILENAME;

        /**
         * If the file can be created and uploaded. Let's try to write it.
         */
        try {
            $stylesheet = fopen($file, 'w') or $this->throw_error(400, "Cannot create file {$file}");
            fwrite($stylesheet, $fonts);
            fclose($stylesheet);
            wp_die(__('Stylesheet was successfully generated and added to your theme\'s header.'));
        } catch (Exception $e) {
            $this->throw_error($e->getCode(), __("Stylesheet could not be generated: $e"));
        }
    }

    /**
     * Insert promo material :)
     *
     * The alignment is crooked, so it'll look nice in the stylesheet.
     */
    private function insert_promo()
    {
        $this->fonts[] = "/** 
 * This file is automagically generated by OMGF
 *
 * @author: Daan van den Bergh
 * @copyright: (c) 2019 Daan van den Bergh
 * @url: " . OMGF_SITE_URL . "
 */";
    }

    /**
     * Prepare fonts for generation.
     */
    private function process_fonts($fonts)
    {
        $fontDisplay = OMGF_DISPLAY_OPTION;

        $i = 1;

        foreach ($fonts as $font) {
            $fontFamily     = sanitize_text_field($font->font_family);
            $fontStyle      = sanitize_text_field($font->font_style);
            $fontWeight     = sanitize_text_field($font->font_weight);
            $fontUrlEot     = esc_url_raw($font->url_eot);
            $fontUrlWoffTwo = esc_url_raw($font->url_woff2);
            $fontUrlWoff    = esc_url_raw($font->url_woff);
            $fontUrlTtf     = esc_url_raw($font->url_ttf);
            $locals         = explode(',', sanitize_text_field($font->local));
            $fontLocal      = isset($locals[0]) ? $locals[0] : $fontFamily . " " . ucfirst($fontStyle);
            $fontLocalDash  = isset($locals[1]) ? $locals[1] : $fontFamily . "-" . ucfirst($fontStyle);

            /**
             * The alignment is crooked, so it'll look nice in the stylesheet.
             */
            $this->fonts[$i] = "@font-face { \n";
            $this->fonts[$i] .= "  font-family: '$fontFamily'; \n";
            $this->fonts[$i] .= "  font-display: $fontDisplay; \n";
            $this->fonts[$i] .= "  font-style: $fontStyle; \n";
            $this->fonts[$i] .= "  font-weight: $fontWeight; \n";
            $this->fonts[$i] .= isset($fontUrlEot) ? "  src: url('$fontUrlEot'); /* IE9 Compatible */ \n" : '';
            $this->fonts[$i] .= "  src: local('$fontLocal'), local('$fontLocalDash'), \n";
            $this->fonts[$i] .= isset($fontUrlWoffTwo) ? "  url('$fontUrlWoffTwo') format('woff2'), /* Super Modern Browsers */ \n" : '';
            $this->fonts[$i] .= isset($fontUrlWoff) ? "  url('$fontUrlWoff') format('woff'), /* Modern Browsers */ \n" : '';
            $this->fonts[$i] .= "  url('$fontUrlTtf') format('truetype'); /* Safari, Android, iOS */ \n";
            $this->fonts[$i] .= "}";

            $i++;
        }
    }
}
