<?php
/**
 * Auto-generated by OMGF - do not edit manually.
 * This file registers Cloudflare cache purge actions early enough in the WordPress load order.
 * It is automatically removed when OMGF is deactivated.
 */

add_filter( 'cloudflare_purge_url_actions', function ( $actions ) {
	$actions[] = 'omgf_cloudflare_purge_url';

	return $actions;
} );

add_filter( 'cloudflare_purge_everything_actions', function ( $actions ) {
	$actions[] = 'omgf_optimize_succeeded';

	return $actions;
} );
