<?php
/* * * * * * * * * * * * * * * * * * * * *
 *
 *  ██████╗ ███╗   ███╗ ██████╗ ███████╗
 * ██╔═══██╗████╗ ████║██╔════╝ ██╔════╝
 * ██║   ██║██╔████╔██║██║  ███╗█████╗
 * ██║   ██║██║╚██╔╝██║██║   ██║██╔══╝
 * ╚██████╔╝██║ ╚═╝ ██║╚██████╔╝██║
 *  ╚═════╝ ╚═╝     ╚═╝ ╚═════╝ ╚═╝
 *
 * @package  : OMGF
 * @author   : Daan van den Bergh
 * @copyright: (c) 2020 Daan van den Bergh
 * @url      : https://daan.dev
 * * * * * * * * * * * * * * * * * * * */

defined('ABSPATH') || exit;

$db      = new OMGF_DB();
$utmTags = '?utm_source=omgf&utm_medium=plugin&utm_campaign=settings';
?>
<div class="omgf-generate-stylesheet">
    <h3><?= __('Generate Stylesheet', 'host-webfonts-local'); ?></h3>
    <p>
        <?= __('<strong>Search</strong> returns all available subsets and font styles for each font family. <strong>Auto Detect</strong> only returns subsets and font styles that\'re used by your installed theme and plugins.', 'host-webfonts-local'); ?>
    </p>
    <p>
        <?= __('You can <strong>Search</strong> by either using a comma separated list (e.g. Open Sans, Poppins, Roboto) or by searching for each font family one by one.', 'host-webfonts-local'); ?>
    </p>
    <div class="omgf-search-section">
        <div class="omgf-search-box">
            <input type="text" id="omgf-search" class="form-input-tip ui-autocomplete-input" placeholder="<?php _e('Search... [e.g. Roboto, Open Sans, Poppins]', 'host-webfonts-local'); ?>" />
            <input type="button" id="omgf-search-subsets" class="button button-primary button-hero" value="<?php _e('Search', 'host-webfonts-local'); ?>"/>
            <input type="button" id="omgf-auto-detect" class="button button-secondary button-hero" value="<?= __('Auto Detect', 'host-webfonts-local'); ?>" />
        </div>
        <table>
            <caption><?php _e('Available subsets', 'host-webfonts-local'); ?></caption>
            <tbody id="omgf-subsets">
            <?php
            $subsetFonts = $db->get_subsets();
            ?>
            <?php if ($subsetFonts): ?>
                <?php foreach ($subsetFonts as $subsetFont): ?>
                    <tr valign="top" id="<?= $subsetFont['subset_font']; ?>">
                        <td>
                            <label>
                                <input readonly type="text" class="omgf-subset-font-family" data-font-family="<?= $subsetFont['subset_font']; ?>" value="<?= $subsetFont['subset_family']; ?>" />
                            </label>
                        </td>
                        <?php foreach ($subsetFont['available_subsets'] as $availableSubset): ?>
                            <td>
                                <label>
                                    <?php $checked = in_array($availableSubset, $subsetFont['selected_subsets']) ? 'checked' : ''; ?>
                                    <input class="omgf-subset" data-subset-font-family="<?= $subsetFont['subset_font']; ?>" value="<?= $availableSubset; ?>" type="checkbox" <?= $checked; ?> />
                                    <?= $availableSubset; ?>
                                </label>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            <tr align="center">
                <td class="omgf-subsets-search" align="right"><span class="omgf-apply help" style="display: none;"><strong><?= __('Search Font Styles', 'host-webfonts-local'); ?></strong></span></td>
                <td><a class="button-primary omgf-apply button font-styles-search" href="#" style="display: none;"><span class="dashicons-before dashicons-search">&nbsp;</span></a></td>
            </tr>
            <?php else: ?>
                <tr colspan="3">
                    <td>
                        <em><?php _e('No subsets found. Use <strong>Search</strong> or <strong>Auto Detect</strong> start.', 'host-webfonts-local'); ?></em>
                    </td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <table id="omgf-font-styles-list">
            <caption><?php _e('Available font styles', 'host-webfonts-local'); ?></caption>
            <?php
            $savedFonts = $db->get_total_fonts();
            ?>
            <?php if ($savedFonts && $subsetFonts): ?>
                <thead align="center">
                <th>
                    <?= __('Font Family', 'host-webfonts-local'); ?>
                </th>
                <th>
                    <?= __('Font Style', 'host-webfonts-local'); ?>
                </th>
                <th>
                    <?= __('Font Weight', 'host-webfonts-local'); ?>
                </th>
                <th>
                    <?= __('Preload? *', 'host-webfonts-local'); ?>
                </th>
                <th></th>
                </thead>
                <tbody id="omgf-font-styles">
                <?php foreach ($savedFonts as $font):
                    $fontId = $font['font_id'];
                    ?>
                    <tr class="omgf-font-style" data-font-id="<?= $fontId; ?>" id="row-<?= $fontId; ?>">
                        <td style="width: 195px;">
                            <input readonly type="text" value="<?= $font['font_family']; ?>" />
                        </td>
                        <td style="width: 150px;">
                            <input style="width: 150px;" readonly type="text" value="<?= $font['font_style']; ?>" />
                        </td>
                        <td style="width: 100px;">
                            <input style="width: 100px;" readonly type="text" value="<?= $font['font_weight']; ?>" />
                        </td>
                        <td align="center" style="width: 45px;">
                            <input type="checkbox" class="omgf-font-preload" value="<?= $fontId; ?>" <?= $font['preload'] == 1 ? 'checked' : ''; ?> />
                        </td>
                        <td style="width: 45px;">
                            <input type="hidden" value="<?= $fontId; ?>" />
                            <input type="hidden" value="<?= $font['local']; ?>" />
                            <input type="hidden" value="<?= $font['url_ttf']; ?>" />
                            <input type="hidden" value="<?= $font['url_woff']; ?>" />
                            <input type="hidden" value="<?= $font['url_woff2']; ?>" />
                            <input type="hidden" value="<?= $font['url_eot']; ?>" />
                            <span data-row="row-<?= $fontId; ?>" class="omgf-font-remove notice-dismiss">&nbsp;</span>
                        </td>
                    </tr>
                <?php endforeach; ?>
                    <!-- The navbar at the bottom of the table. -->
                    <tr id="font-styles-nav" class="sticky bottom" align="right">
                        <td colspan="3"><span class="omgf-apply help font-styles" style="display: none;"><strong><?= __('Apply Changes', 'host-webfonts-local'); ?></strong></span></td>
                        <td align="left" colspan="2" style="width: 100px"><a class="button-primary omgf-apply button font-styles" href="#" style="display: none;"><span class="dashicons-before dashicons-yes"></span> <?= __('Apply', 'host-webfonts-local'); ?></a></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <span class="description">* <?= __('Only the <strong>woff2</strong> format is preloaded, since this format is widely supported by Modern Browsers which support preload.', 'host-webfonts-local'); ?></span>
                        </td>
                    </tr>
                </tbody>
            <?php else: ?>
                <tr>
                    <td>
                        <em><?php _e('No fonts found. Choose <strong>subsets</strong> to start searching for fonts.', 'host-webfonts-local'); ?></em>
                    </td>
                </tr>
            <?php endif; ?>
        </table>
    </div>

    <div id="omgf-control-panel">
        <input type="button" id="omgf-download" class="button-primary" value="<?php _e('Download Fonts', 'host-webfonts-local'); ?>" />
        <input type="button" id="omgf-generate" class="button-secondary" value="<?php _e('Generate Stylesheet', 'host-webfonts-local'); ?>" />
        <a id="omgf-empty" class="button-cancel"><?php _e('Empty Cache Directory', 'host-webfonts-local'); ?></a>
    </div>
</div>
<div class="omgf-loading" style="display: none;">
    <span class="spinner is-active"> </span>
</div>