<?php
/* * * * * * * * * * * * * * * * * * * * *
 *
 *  ██████╗ ███╗   ███╗ ██████╗ ███████╗
 * ██╔═══██╗████╗ ████║██╔════╝ ██╔════╝
 * ██║   ██║██╔████╔██║██║  ███╗█████╗
 * ██║   ██║██║╚██╔╝██║██║   ██║██╔══╝
 * ╚██████╔╝██║ ╚═╝ ██║╚██████╔╝██║
 *  ╚═════╝ ╚═╝     ╚═╝ ╚═════╝ ╚═╝
 *
 * @package  : OMGF
 * @author   : Daan van den Bergh
 * @copyright: (c) 2019 Daan van den Bergh
 * @url      : https://daan.dev
 * * * * * * * * * * * * * * * * * * * */

defined('ABSPATH') || exit;

$db = new OMGF_DB();
$utmTags = '?utm_source=omgf&utm_medium=plugin&utm_campaign=settings';
?>
<div class="">
    <h3><?php _e('Generate Stylesheet', 'host-webfonts-local'); ?></h3>
    <div class="hwl-search-box">
        <input type="text" name="search-field"
               id="omgf-search" class="form-input-tip ui-autocomplete-input" placeholder="<?php _e('Search... (e.g. Roboto,Open Sans)', 'host-webfonts-local'); ?>"/>
        <input type="button" name="search-btn"
               id="omgf-search-subsets" class="button button-primary button-hero" value="<?php _e('Search', 'host-webfonts-local'); ?>"/> - <?= __('or', 'host-webfonts-local'); ?> -
        <input type="button" name="detect-btn" id="omgf-auto-detect" class="button button-secondary button-hero" value="<?= __('Auto-detect', 'host-webfonts-local'); ?>" />
    </div>
    <p class="description">
        <?= __('Default WordPress fonts are left unchecked by default. Enable them only if you\'re sure that your theme uses them.', 'host-webfonts-local'); ?><br />
        <a href="<?= OMGF_SITE_URL; ?>/how-to/find-wordpress-website-fonts/<?= $utmTags; ?>"><?= __('Which fonts does my theme use?', 'host-webfonts-local'); ?></a>
    </p>
    <table>
        <tr id="row" valign="top">
            <th align="left" colspan="3"><?php _e('Available subsets', 'host-webfonts-local'); ?></th>
        </tr>
        <tbody id="hwl-subsets">
        <?php
        $subsetFonts = $db->get_subsets();
        ?>
        <?php if ($subsetFonts): ?>
            <?php foreach ($subsetFonts as $subsetFont): ?>
                <tr valign="top" id="<?= $subsetFont['subset_font']; ?>">
                    <td>
                        <label>
                            <input readonly type="text" class="omgf-subset-font-family" data-font-family="<?= $subsetFont['subset_font']; ?>" value="<?= $subsetFont['subset_family']; ?>" />
                        </label>
                    </td>
                    <?php foreach ($subsetFont['available_subsets'] as $availableSubset): ?>
                        <td>
                            <label>
                                <?php $checked = in_array($availableSubset, $subsetFont['selected_subsets']) ? 'checked="checked"' : ''; ?>
                                <input class="omgf-subset" name="<?= $subsetFont['subset_font']; ?>" value="<?= $availableSubset; ?>" type="checkbox" <?= $checked; ?> />
                                <?= $availableSubset; ?>
                            </label>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
    </table>
    <table>
        <tr valign="top">
            <th align="left" colspan="3"><?php _e('Available fonts', 'host-webfonts-local'); ?></th>
        </tr>
    </table>
    <table id="hwl-results">
        <thead align="center">
        <th>
            <?= __('Font Family', 'host-webfonts-local'); ?>
        </th>
        <th>
            <?= __('Font Style', 'host-webfonts-local'); ?>
        </th>
        <th>
            <?= __('Font Weight', 'host-webfonts-local'); ?>
        </th>
        <th>
            <?= __('Preload? *', 'host-webfonts-local'); ?>
        </th>
        <th></th>
        </thead>
        <?php
        $savedFonts = $db->get_total_fonts();
        ?>
        <?php if ($savedFonts && $subsetFonts): ?>
        <tbody align="center" id="omgf-font-styles">
            <?php foreach ($savedFonts as $font):
                $fontId = $font['font_id'];
                $arrayPath = "caos_webfonts_array][$fontId]";
                ?>
                <tr class="omgf-font-style" data-font-id="<?= $fontId; ?>" id="row-<?= $fontId; ?>" valign="top" align="center">
                    <td>
                        <input readonly type="text" value="<?= $font['font_family']; ?>" name="<?= $arrayPath; ?>[font-family]"/>
                    </td>
                    <td>
                        <input readonly type="text" value="<?= $font['font_style']; ?>" name="<?= $arrayPath; ?>[font-style]"/>
                    </td>
                    <td>
                        <input readonly type="text" value="<?= $font['font_weight']; ?>" name="<?= $arrayPath; ?>[font-weight]"/>
                    </td>
                    <td>
                        <input type="checkbox" class="omgf-font-preload" data-preload="<?= $fontId; ?>" value="1" <?= $font['preload'] == 1 ? 'checked' : ''; ?> name="<?= $arrayPath; ?>[preload]"/>
                    </td>
                    <td>
                        <input type="hidden" value="<?= $fontId; ?>" name="<?= $arrayPath; ?>[id]"/>
                        <input type="hidden" value="<?= $font['local']; ?>" name="<?= $arrayPath; ?>[local]"/>
                        <input type="hidden" value="<?= $font['url_ttf']; ?>" name="<?= $arrayPath; ?>[url][ttf]"/>
                        <input type="hidden" value="<?= $font['url_woff']; ?>" name="<?= $arrayPath; ?>[url][woff]"/>
                        <input type="hidden" value="<?= $font['url_woff2']; ?>" name="<?= $arrayPath; ?>[url][woff2]"/>
                        <input type="hidden" value="<?= $font['url_eot']; ?>" name="<?= $arrayPath; ?>[url][eot]"/>
                        <span data-row="row-<?= $fontId; ?>" class="omgf-font-remove notice-dismiss">&nbsp;</span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <?php endif; ?>
        <tbody id="hwl-warning">
        <tr class="loading" style="display: none;">
            <td colspan="3" align="center">
                <span class="spinner"></span>
            </td>
        </tr>
        <tr class="error" style="display: none;">
            <td colspan="3" align="center"><?php _e('No fonts available.', 'host-webfonts-local'); ?></td>
        </tr>
        </tbody>
    </table>

    <table>
        <tbody>
        <tr>
            <td colspan="3">
                <span class="description">* <?= __('Only the <strong>woff2</strong> format is preloaded, since this format is widely supported by Modern Browsers which support preload.'); ?></span>
            </td>
        </tr>
        <tr valign="center">
            <td>
                <input type="button" name="save-btn"
                       id="omgf-download" class="button-primary" value="<?php _e('Download Fonts', 'host-webfonts-local'); ?>"/>
            </td>
            <td>
                <input type="button" name="generate-btn"
                       id="omgf-generate" class="button-secondary" value="<?php _e('Generate Stylesheet', 'host-webfonts-local'); ?>"/>
            </td>
            <td>
                <a name="empty-btn"
                   id="omgf-empty" class="button-cancel"><?php _e('Empty Cache Directory', 'host-webfonts-local'); ?></a>
            </td>
        </tr>
        <tr valign="center">
            <?php
            $downloaded = $db->get_download_status()['downloaded'];
            $total      = $db->get_download_status()['total'];
            $width      = $downloaded && $total ? (100 / $total) * $downloaded : 0;
            ?>
            <td colspan="5">
                <div class="caos-status-total-bar" style="">
                    <div id="caos-status-progress-bar" style="width: <?= $width; ?>%;">
                        <span class="caos-status-progress-percentage"><?= $width . '%'; ?></span>
                    </div>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
